services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
